export const ContentData = `
    <h1>on (part) collide with (other) at (Velocity) and (impulse)</h1>
    <vizzy-div>
        <vizzy-event>
            <vizzy-text>on</vizzy-text>
            <vizzy-parameter>
                <vizzy-text>part</vizzy-text>
            </vizzy-parameter>
            <vizzy-text>collide with</vizzy-text>
            <vizzy-parameter>
                <vizzy-text>othert</vizzy-text>
            </vizzy-parameter>
            <vizzy-text>at</vizzy-text>
            <vizzy-parameter>
                <vizzy-text>velocity</vizzy-text>
            </vizzy-parameter>
            <vizzy-text>and</vizzy-text>
            <vizzy-parameter>
                <vizzy-text>impulse</vizzy-text>
            </vizzy-parameter>
        </vizzy-event>
    </vizzy-div>        
    <p>当飞船发生碰撞时触发，并赋予里面的黄色参数新的数值，里面的参数可以被拖动并调用，用法和自定义变量相同。</p> 

    <h2>参数列表</h2>
    <table  style="width: 100%;">
        <thead>
            <tr>
                <th>参数</th>
                <th>类型</th>
                <th>定义</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>
                    <vizzy-div>
                        <vizzy-parameter>
                            <vizzy-text>part</vizzy-text>
                        </vizzy-parameter>
                    </vizzy-div>
                </td>
                <td>Num</td>
                <td>收到撞击的零件</td>
            </tr>
            <tr>
                <td>
                    <vizzy-div>
                        <vizzy-parameter>
                            <vizzy-text>othert</vizzy-text>
                        </vizzy-parameter>
                    </vizzy-div>
                </td>
                <td>Text</td>
                <td>另一个飞船的名字</td>
            </tr>
             <tr>
                <td>
                    <vizzy-div>
                        <vizzy-parameter>
                            <vizzy-text>velocity</vizzy-text>
                        </vizzy-parameter>
                    </vizzy-div>
                </td>
                <td>Num</td>
                <td>撞击的相对速度</td>
            </tr>
             <tr>
                <td>
                    <vizzy-div>
                        <vizzy-parameter>
                            <vizzy-text>impulse</vizzy-text>
                        </vizzy-parameter>
                    </vizzy-div>
                </td>
                <td>Num</td>
                <td>撞击产生的冲量</td>
            </tr>
        </tbody>
    </table>
`;